In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("medical_fixed.csv", encoding = "latin-1")

In [15]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [23]:
df = df.drop(columns = ["sex", "smoker", "region", "charges"])

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   bmi       1338 non-null   float64
 2   children  1338 non-null   int64
dtypes: float64(1), int64(2)
memory usage: 31.5 KB

In [25]:
df.describe().round(3)

            age       bmi  children
count  1338.000  1338.000  1338.000
mean     39.207    30.663     1.095
std      14.050     6.098     1.205
min      18.000    15.960     0.000
25%      27.000    26.296     0.000
50%      39.000    30.400     1.000
75%      51.000    34.694     2.000
max      64.000    53.130     5.000

In [28]:
X1 = df.iloc[:,:] # standard scaling

In [44]:
X2 = df.iloc[:,:] # min/max scaling

In [ ]:
# STANDARDIZATION

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
scaleStandard = StandardScaler()

In [37]:
X1 = scaleStandard.fit_transform(X1)

In [39]:
X1 = pd.DataFrame(X1, columns = ["age", "bmi", "children"])

In [41]:
X1.head()

        age       bmi  children
0 -1.438764 -0.453320 -0.908614
1 -1.509965  0.509621 -0.078767
2 -0.797954  0.383307  1.580926
3 -0.441948 -1.305531 -0.908614
4 -0.513149 -0.292556 -0.908614

In [43]:
X1.describe().round(3)

            age       bmi  children
count  1338.000  1338.000  1338.000
mean     -0.000    -0.000    -0.000
std       1.000     1.000     1.000
min      -1.510    -2.412    -0.909
25%      -0.869    -0.716    -0.909
50%      -0.015    -0.043    -0.079
75%       0.840     0.661     0.751
max       1.765     3.686     3.241

In [45]:
# NORMALIZATION

In [46]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
scaleMinMax = MinMaxScaler(feature_range = (0,1))

In [48]:
X2 = scaleMinMax.fit_transform(X2)

In [49]:
X2 = pd.DataFrame(X2, columns = ["age", "bmi", "children"])

In [50]:
X2.head()

        age       bmi  children
0  0.021739  0.321227       0.0
1  0.000000  0.479150       0.2
2  0.217391  0.458434       0.6
3  0.326087  0.181464       0.0
4  0.304348  0.347592       0.0

In [51]:
X2.describe().round(3)

            age       bmi  children
count  1338.000  1338.000  1338.000
mean      0.461     0.396     0.219
std       0.305     0.164     0.241
min       0.000     0.000     0.000
25%       0.196     0.278     0.000
50%       0.457     0.388     0.200
75%       0.717     0.504     0.400
max       1.000     1.000     1.000