In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Pearl_Jam_Tour2.csv', encoding ='unicode_escape')

In [4]:
df

,City Population,Continent,Venue Capacity,Day of Week,Multiple Concerts,Sold Out
0,7971301,North America,21024,Tuesday,0,0
1,7378334,Africa,38741,Monday,1,1
2,6787781,Europe,18247,Friday,0,0
3,28653498,Europe,32439,Friday,1,1
4,936124,Europe,48753,Thursday,1,1
...,...,...,...,...,...,...
495,33499165,South America,49539,Sunday,1,1
496,6047931,Oceania,5022,Sunday,0,0
497,18945067,Europe,38232,Wednesday,0,1
498,33739915,Oceania,36476,Monday,0,1
499,25119676,Oceania,5726,Sunday,1,0

In [5]:
df2 = pd.get_dummies(df[['Continent', 'Day of Week']])

In [6]:
df2

,Continent_Africa,Continent_Asia,Continent_Europe,Continent_North America,Continent_Oceania,Continent_South America,Day of Week_Friday,Day of Week_Monday,Day of Week_Saturday,Day of Week_Sunday,Day of Week_Thursday,Day of Week_Tuesday,Day of Week_Wednesday
0,False,False,False,True,False,False,False,False,False,False,False,True,False
1,True,False,False,False,False,False,False,True,False,False,False,False,False
2,False,False,True,False,False,False,True,False,False,False,False,False,False
3,False,False,True,False,False,False,True,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,True,False,False,False,True,False,False,False
496,False,False,False,False,True,False,False,False,False,True,False,False,False
497,False,False,True,False,False,False,False,False,False,False,False,False,True
498,False,False,False,False,True,False,False,True,False,False,False,False,False
499,False,False,False,False,True,False,False,False,False,True,False,False,False

In [ ]:
# now splitiing the data for training and testing

In [7]:
df3 = pd.concat([df,df2], axis = 1).drop(columns = ["Continent", "Day of Week"])

In [8]:
df3

,City Population,Venue Capacity,Multiple Concerts,Sold Out,Continent_Africa,Continent_Asia,Continent_Europe,Continent_North America,Continent_Oceania,Continent_South America,Day of Week_Friday,Day of Week_Monday,Day of Week_Saturday,Day of Week_Sunday,Day of Week_Thursday,Day of Week_Tuesday,Day of Week_Wednesday
0,7971301,21024,0,0,False,False,False,True,False,False,False,False,False,False,False,True,False
1,7378334,38741,1,1,True,False,False,False,False,False,False,True,False,False,False,False,False
2,6787781,18247,0,0,False,False,True,False,False,False,True,False,False,False,False,False,False
3,28653498,32439,1,1,False,False,True,False,False,False,True,False,False,False,False,False,False
4,936124,48753,1,1,False,False,True,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,33499165,49539,1,1,False,False,False,False,False,True,False,False,False,True,False,False,False
496,6047931,5022,0,0,False,False,False,False,True,False,False,False,False,True,False,False,False
497,18945067,38232,0,1,False,False,True,False,False,False,False,False,False,False,False,False,True
498,33739915,36476,0,1,False,False,False,False,True,False,False,True,False,False,False,False,False
499,25119676,5726,1,0,False,False,False,False,True,False,False,False,False,True,False,False,False

In [9]:
X = df3.drop(['Sold Out'], axis = 1)

In [10]:
y = df3['Sold Out']

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 23, test_size = 0.2)

In [16]:
from sklearn.naive_bayes import GaussianNB

In [19]:
gnb = GaussianNB()

In [20]:
gnb.fit(X_train, y_train)

GaussianNB()

In [30]:
y_pred = gnb.predict(X_test)

In [31]:
from sklearn.metrics import classification_report

In [32]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.73      0.81        45
           1       0.81      0.95      0.87        55

    accuracy                           0.85       100
   macro avg       0.86      0.84      0.84       100
weighted avg       0.86      0.85      0.85       100

In [33]:
print(confusion_matrix(y_test, y_pred))

[[33 12]
 [ 3 52]]

In [34]:
gnb.score(X_train, y_train)

0.9

In [35]:
gnb.score(X_test, y_test)

0.85

In [36]:
# add in parameters

In [37]:
param_grid = {
    'var_smoothing' : [0.00000001, 0.000000001, 0.000000001]
}

In [39]:
from sklearn.model_selection import GridSearchCV

In [41]:
grid_search = GridSearchCV(gnb, param_grid, cv = 5, scoring = 'accuracy', n_jobs = -1)

In [42]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': [1e-08, 1e-09, 1e-09]},
             scoring='accuracy')

In [43]:
grid_search.best_params_

{'var_smoothing': 1e-08}

In [44]:
grid_search.best_score_

np.float64(0.8950000000000001)